import type { ThemeConfig } from "antd"

export const theme: ThemeConfig = {
  components: {
    Breadcrumb: {
      itemColor: "#FFF",
      lastItemColor: "rgba(255, 255, 255, 0.55)",
      linkHoverColor: "rgba(255, 255, 255, 0.55)",
      linkColor: "#FFF",
      colorBgTextHover: "transparent",
      separatorColor: "#FFF",
    },
    Input: {
      colorTextPlaceholder: "#a0aec0",
      colorTextQuaternary: "#a0aec0",
      colorText: "#a0aec0",
    },
    Select: {
      colorTextPlaceholder: "#a0aec0",
      colorBgContainer: "#1e2d47",
      colorBorder: "#1e2d47",
      activeBorderColor: "#1e2d47",
      hoverBorderColor: "#1e2d47",
      borderRadius: 8,
      colorText: "#a0aec0",
      colorTextDisabled: "#4a5568",
      colorIcon: "#a0aec0",
      colorIconHover: "#a0aec0",
      colorBgElevated: "#24324F",
      colorTextLightSolid: "#a0aec0",
      controlItemBgActive: "#30456B",
      controlItemBgHover: "#2b3e63",
      colorTextQuaternary: "#a0aec0",
    },
    DatePicker: {
      colorTextPlaceholder: "#a0aec0",
      colorBgContainer: "#1e2d47",
      colorBorder: "#1e2d47",
      activeBorderColor: "#1e2d47",
      hoverBorderColor: "#1e2d47",
      borderRadius: 8,
      colorText: "#a0aec0",
      colorTextDisabled: "#4a5568",
      colorIcon: "#a0aec0",
      colorIconHover: "#a0aec0",
      colorBgElevated: "#24324F",
      colorTextLightSolid: "#a0aec0",
      colorTextHeading: "#ffffff",
      controlItemBgActive: "#30456B",
      controlItemBgHover: "#2b3e63",
      colorTextQuaternary: "#a0aec0",
    },
    Pagination: {
      colorBgContainer: "#1e2d47",
      colorBorder: "#1e2d47",
      colorText: "#a0aec0",
      colorTextDisabled: "#4a5568",
      colorBgTextHover: "#2b3e63",
      colorBgTextActive: "#30456B",
      borderRadius: 50,
    },
    Typography: {
      colorText: "#FFF",
    },
  },
  token: {
    colorPrimary: "#1890ff",
    colorTextTertiary: "#a0aec0",
  },
}
